<?php
/**
 * acf_custom_fields.php
 * add php generated acf fields here, Not necessary for all ACFs... but it is a good idea to add theme critical ACFs here to stop clients from editing core functionality by accident.
 *
 * @package starter-theme
 * @author Philip Bradbury
 * @created 03/04/2023 12:45
 * @since 1.0
 * @updated 1.0
 */

/**
 * Options Page setup
 */
if ( function_exists( 'acf_add_options_page' ) )
{
    add_action( 'init', 'chelseaoldchurch_add_acf_archive_setting_pages', 10 );
    function chelseaoldchurch_add_acf_archive_setting_pages()
    {
        acf_add_options_page( array(
            'page_title' => 'Theme Settings',
            'menu_title' => 'Theme Settings',
            'menu_slug'  => 'default-settings',
            'position'   => '2',
            'icon_url'   => 'dashicons-database',
            'capability' => 'edit_posts',
            'redirect'   => false
        ) );

        acf_add_options_sub_page( array(
            'page_title'  => "Weekly Tab Settings",
            'menu_title'  => "Weekly Tab",
            'parent_slug' => 'edit.php?post_type=week',
            'position'    => '2',
        ) );
        $post_types_settings_pages = [
            'event'  => [
                    'post_type'   => 'event',
                    'page_title'  => 'Events Settings',
                    'page_name'   => 'acf-options-events-settings',
                    'parent_slug' => 'edit.php?post_type=event',
            ],
            'staff'  => [
                'post_type'   => 'staff',
                'page_title'  => 'Staff Settings',
                'page_name'   => 'acf-options-staff-settings',
                'parent_slug' => 'edit.php?post_type=staff',
            ],
            'clergy' => [
                'post_type'   => 'clergy',
                'page_title'  => 'Clergy Settings',
                'page_name'   => 'acf-options-clergy-settings',
                'parent_slug' => 'edit.php?post_type=clergy',
            ],
            'story' => [
                'post_type'   => 'story',
                'page_title'  => 'Story Settings',
                'page_name'   => 'acf-options-story-settings',
                'parent_slug' => 'edit.php?post_type=story',
            ],
        ];
        foreach ( $post_types_settings_pages as $key => $post_type )
        {
            acf_add_options_sub_page( array(
                'page_title'  => $post_type[ 'page_title' ],
                'menu_title'  => $post_type[ 'page_title' ],
                'parent_slug' => 'edit.php?post_type=' . $key,
                'position'    => '2',
            ) );

            chelseaoldchurch_archive_post_type_fields( $post_type[ 'post_type' ], $post_type[ 'page_name' ], $post_type[ 'page_title' ] );
        }
    }

}

if( function_exists('acf_add_local_field_group') ):

    add_action('init','chelseaoldchurch_add_links_information_meta_box',10);
    function chelseaoldchurch_add_links_information_meta_box(){
        acf_add_local_field_group(array(
            'key' => 'group_642de1c5822e8',
            'title' => 'Page links',
            'fields' => array(
                array(
                    'key' => 'field_642de2af448ea',
                    'label' => 'Show Page Links',
                    'name' => 'show_page_links',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => 'On',
                    'ui_off_text' => 'Off',
                ),
                array(
                    'key' => 'field_642de38e448ec',
                    'label' => 'Page Link Position',
                    'name' => 'page_link_position',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_642de2af448ea',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => 'Top',
                    'ui_off_text' => 'Bottom',
                ),
                array(
                    'key' => 'field_642de20c448e8',
                    'label' => 'Page links',
                    'name' => 'page_links',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_642de2af448ea',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 4,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_642de228448e9',
                            'label' => 'Add Page links',
                            'name' => 'add_page_links',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'page',
                                1 => 'event',
                            ),
                            'taxonomy' => '',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => 'object',
                            'ui' => 1,
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                ),
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'event',
                    ),
                ),
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'story',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
        ));

    }

    add_action('init','chelseaoldchurch_add_event_information_meta_box',10);
    function chelseaoldchurch_add_event_information_meta_box(){
        acf_add_local_field_group(array(
            'key' => 'group_5c065ba4179ee',
            'title' => 'Event information',
            'fields' => array(
                array(
                    'key' => 'field_5c0f766463c27',
                    'label' => 'Event Information',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5e710e61d37fb',
                    'label' => 'Date & Time',
                    'name' => 'event_date_time',
                    'aria-label' => '',
                    'type' => 'date_time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d H:i:s',
                    'return_format' => 'F j, Y H:i:s',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'field_5f33bad9bb351',
                    'label' => 'Event meta',
                    'name' => 'event_meta',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5c0e9c28832b9',
                    'label' => 'Information to appear in What\'s on this Week',
                    'name' => 'list_information',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_5c0f7686dc725',
                    'label' => 'More event info',
                    'name' => '',
                    'aria-label' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5c0f76b0dc728',
                    'label' => 'Display extra info on red background?',
                    'name' => 'show_event_info',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                ),
                array(
                    'key' => 'field_5c0f768fdc726',
                    'label' => 'Event Title (red background)',
                    'name' => 'event_info_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5c0f76b0dc728',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5c0f7699dc727',
                    'label' => 'Event content (red background)',
                    'name' => 'event_info_content',
                    'aria-label' => '',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_5c0f76b0dc728',
                                'operator' => '==',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 1,
                    'delay' => 0,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'event',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
        ));

    }

    add_action( 'init', 'chelseaoldchurch_add_weekly_information_meta_box', 10 );
    function chelseaoldchurch_add_weekly_information_meta_box()
    {
        acf_add_local_field_group(array(
            'key' => 'group_5c065f7da2df1',
            'title' => 'Week Information',
            'fields' => array(
                array(
                    'key' => 'field_5c06648252cdf',
                    'label' => 'Event Week Day',
                    'name' => 'event_week_day',
                    'aria-label' => '',
                    'type' => 'date_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y-m-d',
                    'return_format' => 'Y-m-d',
                    'first_day' => 0,
                ),
                array(
                    'key' => 'field_5c0fab42eb9dd',
                    'label' => 'Listing Tab Title',
                    'name' => 'listing_tab_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'On this week',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5c10e16ac9b99',
                    'label' => 'Listing Tab Button Title',
                    'name' => 'listing_tab_button_title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'View full diary',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5c0e5598ede9b',
                    'label' => 'Day Based Information',
                    'name' => 'day_based_information',
                    'aria-label' => '',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        '5c0e55c2a72b8' => array(
                            'key' => '5c0e55c2a72b8',
                            'name' => 'event_day',
                            'label' => 'Event Day',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5c0e57997f7ad',
                                    'label' => 'Event Day',
                                    'name' => 'event_day',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'monday' => 'Monday',
                                        'tuesday' => 'Tuesday',
                                        'wednesday' => 'Wednesday',
                                        'thursday' => 'Thursday',
                                        'friday' => 'Friday',
                                        'saturday' => 'Saturday',
                                        'sunday' => 'Sunday',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 1,
                                    'ajax' => 0,
                                    'return_format' => 'label',
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e5663b3d1d',
                                    'label' => 'Date of The Day',
                                    'name' => 'date_of_the_day',
                                    'aria-label' => '',
                                    'type' => 'date_picker',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'display_format' => 'Y-m-d',
                                    'return_format' => 'Y-m-d',
                                    'first_day' => 1,
                                ),
                                array(
                                    'key' => 'field_5c0e56a5b3d1e',
                                    'label' => 'Information',
                                    'name' => 'information',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_5c0e56efb3d1f',
                                    'label' => 'Day Events',
                                    'name' => 'day_events',
                                    'aria-label' => '',
                                    'type' => 'relationship',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'event',
                                    ),
                                    'taxonomy' => '',
                                    'filters' => array(
                                        0 => 'taxonomy',
                                    ),
                                    'elements' => '',
                                    'min' => '',
                                    'max' => '',
                                    'return_format' => 'object',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        'layout_5c0e585bb4e67' => array(
                            'key' => 'layout_5c0e585bb4e67',
                            'name' => 'futured_art',
                            'label' => 'Futured Art',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_5c0e589fb4e6e',
                                    'label' => 'Section Title',
                                    'name' => 'section_title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e587bb4e6c',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'maxlength' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e5887b4e6d',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'aria-label' => '',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 1,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'array',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                    'default_value' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e58e3b4e71',
                                    'label' => 'Show Link',
                                    'name' => 'show_link',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui' => 1,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e58aeb4e6f',
                                    'label' => 'link',
                                    'name' => 'link',
                                    'aria-label' => '',
                                    'type' => 'url',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_5c0e58e3b4e71',
                                                'operator' => '==',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_5c0e58c0b4e70',
                                    'label' => 'link Target',
                                    'name' => 'link_target',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_5c0e58e3b4e71',
                                                'operator' => '==',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        '_self' => 'Self',
                                        '_blank' => 'Blank',
                                    ),
                                    'default_value' => array(
                                    ),
                                    'allow_null' => 0,
                                    'multiple' => 0,
                                    'ui' => 0,
                                    'return_format' => 'value',
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'Add Event Data',
                    'min' => '',
                    'max' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'week',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => false,
        ));

    }

    /**
     * ACF Banner fields
     */
    add_action( 'init', 'chelseaoldchurch_add_weekly_tab_options_meta_box', 10 );
    function chelseaoldchurch_add_weekly_tab_options_meta_box()
    {
        acf_add_local_field_group( array(
            'key'                   => 'group_5d6656f4d9183',
            'title'                 => 'Weekly Tab Settings',
            'fields'                => array(
                array(
                    'key'               => 'field_5d66573300ef3',
                    'label'             => 'Monday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d6658089dca0',
                    'label'             => 'Monday Events',
                    'name'              => 'monday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d66582e9dca1',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d6658089dca0',
                        ),
                        array(
                            'key'               => 'field_5d66583f9dca2',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d6658089dca0',
                        ),
                        array(
                            'key'               => 'field_5d6658709dca3',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d6658089dca0',
                        ),
                        array(
                            'key'               => 'field_5d66588b9dca4',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d6658089dca0',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d66576000ef4',
                    'label'             => 'Tuesday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d6658d60678c',
                    'label'             => 'Tuesday Events',
                    'name'              => 'tuesday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d6658d60678d',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d6658d60678c',
                        ),
                        array(
                            'key'               => 'field_5d6658d60678e',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d6658d60678c',
                        ),
                        array(
                            'key'               => 'field_5d6658d60678f',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d6658d60678c',
                        ),
                        array(
                            'key'               => 'field_5d6658d606790',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d6658d60678c',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d66577200ef5',
                    'label'             => 'Wednesday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d6658ffd9535',
                    'label'             => 'Wednesday Events',
                    'name'              => 'wednesday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d6658ffd9536',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d6658ffd9535',
                        ),
                        array(
                            'key'               => 'field_5d6658ffd9537',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d6658ffd9535',
                        ),
                        array(
                            'key'               => 'field_5d6658ffd9538',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d6658ffd9535',
                        ),
                        array(
                            'key'               => 'field_5d6658ffd9539',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'array',
                            'parent_repeater'   => 'field_5d6658ffd9535',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d66578400ef6',
                    'label'             => 'Thursday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d66592c73990',
                    'label'             => 'Thursday Events',
                    'name'              => 'thursday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d66592c73991',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d66592c73990',
                        ),
                        array(
                            'key'               => 'field_5d66592c73992',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d66592c73990',
                        ),
                        array(
                            'key'               => 'field_5d66592c73993',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d66592c73990',
                        ),
                        array(
                            'key'               => 'field_5d66592c73994',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d66592c73990',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d6657b000ef7',
                    'label'             => 'Friday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d66594973995',
                    'label'             => 'Friday Events',
                    'name'              => 'friday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d66594973996',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d66594973995',
                        ),
                        array(
                            'key'               => 'field_5d66594973997',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d66594973995',
                        ),
                        array(
                            'key'               => 'field_5d66594973998',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d66594973995',
                        ),
                        array(
                            'key'               => 'field_5d66594973999',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d66594973995',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d6657c200ef8',
                    'label'             => 'Saturday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d6659617399a',
                    'label'             => 'Saturday Events',
                    'name'              => 'saturday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d6659617399b',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d6659617399a',
                        ),
                        array(
                            'key'               => 'field_5d6659617399c',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d6659617399a',
                        ),
                        array(
                            'key'               => 'field_5d6659617399d',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d6659617399a',
                        ),
                        array(
                            'key'               => 'field_5d6659617399e',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d6659617399a',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d6657d300ef9',
                    'label'             => 'Sunday',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d66597c7399f',
                    'label'             => 'Sunday Events',
                    'name'              => 'sunday_events',
                    'aria-label'        => '',
                    'type'              => 'repeater',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'collapsed'         => '',
                    'min'               => 0,
                    'max'               => 0,
                    'layout'            => 'table',
                    'button_label'      => 'Add Row',
                    'sub_fields'        => array(
                        array(
                            'key'               => 'field_5d66597c739a0',
                            'label'             => 'Time',
                            'name'              => 'time',
                            'aria-label'        => '',
                            'type'              => 'time_picker',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'display_format'    => 'H:i',
                            'return_format'     => 'H:i',
                            'parent_repeater'   => 'field_5d66597c7399f',
                        ),
                        array(
                            'key'               => 'field_5d66597c739a1',
                            'label'             => 'Title',
                            'name'              => 'title',
                            'aria-label'        => '',
                            'type'              => 'text',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'prepend'           => '',
                            'append'            => '',
                            'maxlength'         => '',
                            'parent_repeater'   => 'field_5d66597c7399f',
                        ),
                        array(
                            'key'               => 'field_5d66597c739a2',
                            'label'             => 'Excerpt',
                            'name'              => 'excerpt',
                            'aria-label'        => '',
                            'type'              => 'textarea',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'default_value'     => '',
                            'placeholder'       => '',
                            'maxlength'         => '',
                            'rows'              => '',
                            'new_lines'         => '',
                            'parent_repeater'   => 'field_5d66597c7399f',
                        ),
                        array(
                            'key'               => 'field_5d66597c739a3',
                            'label'             => 'Link',
                            'name'              => 'link',
                            'aria-label'        => '',
                            'type'              => 'link',
                            'instructions'      => '',
                            'required'          => 0,
                            'conditional_logic' => 0,
                            'wrapper'           => array(
                                'width' => '',
                                'class' => '',
                                'id'    => '',
                            ),
                            'return_format'     => 'url',
                            'parent_repeater'   => 'field_5d66597c7399f',
                        ),
                    ),
                    'rows_per_page'     => 20,
                ),
                array(
                    'key'               => 'field_5d7677c1d85cb',
                    'label'             => 'Buttons',
                    'name'              => '',
                    'aria-label'        => '',
                    'type'              => 'tab',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'placement'         => 'top',
                    'endpoint'          => 0,
                ),
                array(
                    'key'               => 'field_5d76811388dfe',
                    'label'             => 'Button Container',
                    'name'              => 'container',
                    'aria-label'        => '',
                    'type'              => 'flexible_content',
                    'instructions'      => '',
                    'required'          => 0,
                    'conditional_logic' => 0,
                    'wrapper'           => array(
                        'width' => '',
                        'class' => '',
                        'id'    => '',
                    ),
                    'layouts'           => array(
                        'layout_5d76812b453d5' => array(
                            'key'        => 'layout_5d76812b453d5',
                            'name'       => 'file',
                            'label'      => 'File',
                            'display'    => 'table',
                            'sub_fields' => array(
                                array(
                                    'key'               => 'field_5d76814d88e00',
                                    'label'             => 'File text',
                                    'name'              => 'text',
                                    'aria-label'        => '',
                                    'type'              => 'text',
                                    'instructions'      => '',
                                    'required'          => 0,
                                    'conditional_logic' => 0,
                                    'wrapper'           => array(
                                        'width' => '',
                                        'class' => '',
                                        'id'    => '',
                                    ),
                                    'default_value'     => '',
                                    'placeholder'       => '',
                                    'prepend'           => '',
                                    'append'            => '',
                                    'maxlength'         => '',
                                ),
                                array(
                                    'key'               => 'field_5d7681b288e03',
                                    'label'             => 'File',
                                    'name'              => 'file',
                                    'aria-label'        => '',
                                    'type'              => 'file',
                                    'instructions'      => '',
                                    'required'          => 0,
                                    'conditional_logic' => 0,
                                    'wrapper'           => array(
                                        'width' => '',
                                        'class' => '',
                                        'id'    => '',
                                    ),
                                    'return_format'     => 'array',
                                    'library'           => 'all',
                                    'min_size'          => '',
                                    'max_size'          => '',
                                    'mime_types'        => '',
                                ),
                            ),
                            'min'        => '',
                            'max'        => '',
                        ),
                        'layout_5d76814488dff' => array(
                            'key'        => 'layout_5d76814488dff',
                            'name'       => 'link',
                            'label'      => 'Link',
                            'display'    => 'table',
                            'sub_fields' => array(
                                array(
                                    'key'               => 'field_5d76816388e01',
                                    'label'             => 'Link Text',
                                    'name'              => 'text',
                                    'aria-label'        => '',
                                    'type'              => 'text',
                                    'instructions'      => '',
                                    'required'          => 0,
                                    'conditional_logic' => 0,
                                    'wrapper'           => array(
                                        'width' => '',
                                        'class' => '',
                                        'id'    => '',
                                    ),
                                    'default_value'     => '',
                                    'placeholder'       => '',
                                    'prepend'           => '',
                                    'append'            => '',
                                    'maxlength'         => '',
                                ),
                                array(
                                    'key'               => 'field_5d76818488e02',
                                    'label'             => 'Link',
                                    'name'              => 'link',
                                    'aria-label'        => '',
                                    'type'              => 'link',
                                    'instructions'      => '',
                                    'required'          => 0,
                                    'conditional_logic' => 0,
                                    'wrapper'           => array(
                                        'width' => '',
                                        'class' => '',
                                        'id'    => '',
                                    ),
                                    'return_format'     => 'url',
                                ),
                            ),
                            'min'        => '',
                            'max'        => '',
                        ),
                    ),
                    'button_label'      => 'Add Row',
                    'min'               => '',
                    'max'               => '',
                ),
            ),
            'location'              => array(
                array(
                    array(
                        'param'    => 'options_page',
                        'operator' => '==',
                        'value'    => 'acf-options-weekly-tab',
                    ),
                ),
            ),
            'menu_order'            => 0,
            'position'              => 'normal',
            'style'                 => 'default',
            'label_placement'       => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen'        => '',
            'active'                => true,
            'description'           => '',
            'show_in_rest'          => false,
        ) );
    }



endif;